### ISSUE TITLE
Launcher Crashes on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by antonio0831** [an-anime-team/honkers-launcher#58] opened 2024-11-29 11:15 UTC
Machine: Ubuntu 24.04 LTS
Card: NVIDIA Geforce 4060 Laptop
Display: X11

![image](https://github.com/user-attachments/assets/bb461bc2-0bd3-4c8c-93f1-2abf5f38d1fc)
I am unable to get the crash report, as it says it generated a crash report but it actually didn't

**Comment by Mar0xy** [comment] 2024-11-29 11:19
Known issue currently being looked into.

**Comment by krypt0nn** [comment] 2024-11-29 11:22
Caused by https://github.com/an-anime-team/anime-launcher-sdk/pull/16. Will be fixed soon.

**Closed as completed** 2024-11-29 11:50 UTC
